# Generated by Django 5.2.1 on 2025-05-30 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15, unique=True)),
                ('father_email', models.EmailField(max_length=100, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=15, unique=True)),
                ('mother_email', models.EmailField(max_length=100, unique=True)),
                ('pressent_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default='Temp123', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, default='temp123', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='student/'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.parent'),
        ),
    ]
